server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://ab645cfe286724762be9dad8846b238c-1243733161.us-east-1.elb.amazonaws.com:3306/checkr_bc_140_user
    username: dev
    password: Bootcamp@140
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-description: "init"
    baseline-version: 1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true
