server:
  port: ${CANDIDATE_SERVICE_PORT}
spring:
  application:
    name: candidate-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true
