server:
  port: ${ADVERSE_ACTION_SERVICE_PORT}
spring:
  application:
    name: candidate-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/checkr_bc_140_adverse_action
    username: ${USER}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 10
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    debug: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true
