name: Codecov Frontend Scan
on:
  push:
    branches:
      - main # Change it to your main branch.
    paths:
      - "frontend/**" # Specify the frontend folder name.
      - ".github/workflows/frontendBuild.yml" # Replace it correctly with the path to your workflow file.
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codecov:
    if: ( startsWith(github.head_ref, 'FE_') && github.event.pull_request.merged == false ) || ( github.event_name == 'push' )
    name: FE Codecov Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Set the timeout as needed.
    defaults:
      run:
        working-directory: frontend # Change the working-directory to your frontend folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history for accurate analysis.

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/frontend/node_modules # Path to the node_modules folder.
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
        env:
          cache-name: cache-node-modules

      - name: Install the dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm i

      - name: Run tests and generate coverage
        run: npm run test:jest:coverage # Ensure your test script generates a coverage report.

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
